# config/app.yml for rails-settings-cached
defaults: &defaults
  email_subject: "You're an awesome person for using our site!!!!"
  email_body: "Here is the prepended text that will edited"
  email_dates: "03/31/17"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
